version: "3.4"

services:
  laravel9_proxy:
    build: ./docker/nginx
    container_name: laravel9_proxy
    volumes:
      - ./laravel:/usr/share/nginx/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      - "443:443"
    links:
      - laravel9_php-fpm
  laravel9_db:
    build: ./docker/mysql
    container_name: laravel9_db
    environment:
      MYSQL_DATABASE: laravel9
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    expose:
      - "3306"
    ports:
      - "3306:3306"
  laravel9_php-fpm:
    build: ./docker/php
    container_name: laravel9_php-fpm
    expose:
      - "9000"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - laravel9_db
  laravel9_node:
    container_name: laravel9_node
    image: node:12.18.3
    volumes:
      - ./laravel:/var/www/html
    working_dir: /var/www/html
    entrypoint: yarn